### ISSUE TITLE
fork 项目的问题

### ISSUE THREAD

**Issue by neutronest** [MoeOverflow/moe#1]
所以关于项目的具体限制是？

1. 一定要是二次元的项目?

2. fork 项目时请向管理员过审批？

（我暂时删掉了之前的项目）

**Comment by ShinCurry** [comment]
1. 尽量是二次元的吧，因为加入进来的大多都是喜欢动漫的萌豚吧；
2. 不用，这个组织不存在上下级关系。

对于所有的成员没有任何硬性要求和限制，开心就好，😊 我只是不希望被人恶意乱搞而已。
