### ISSUE TITLE
建立一个勋章的 repo

### ISSUE THREAD

**Issue by ppzvpp** [MoeOverflow/moe#3]
可以建立一个 repo 把使用过的勋章都收集起来，也方便讨论和 pr 新的勋章呢ww

**Comment by ShinCurry** [comment]
这个我想过的，但是我个人觉得这样是不是算做滥用 Github（而且，这个 repo 已经这样做了），毕竟在一个空项目里提各种 issues 感觉不太好。或者考虑另外一种方案，建一个 telegram 群来讨论这些问题。我考虑过这事，但是考虑到可能没什么好讲的就一直没建。征求你们的意见。

**Comment by soruly** [comment]
個人沒什麼偏好, 只要不是國內的通訊軟件就好

**Comment by yaqinking** [comment]
建立 repo 放勋章这个，没绘画的版权最好不要这样做…
在空项目里加 issue 讨论问题，这个没啥问题的吧，以交流为目的。（如果是在 Telegram 里聊天讨论的话，记录不能在网络上公开搜索到，是一个弊端，在 issue 里讨论也许能给后来者作个参考什么的，并且也能作为历史回顾纪录。）

**Comment by ppzvpp** [comment]
git 并不局限于管理代码，GitHub 在 ToS 里面也没有限制内容和使用方式，我认为没有什么不妥的
我觉得聊天工具不适合用来做讨论，有一个论坛之类的比较好(
对了，勋章也可以挂在网站上(总之想要收集起来ww

**Comment by soruly** [comment]
Gitter呢?

**Comment by ShinCurry** [comment]
(:3_ヽ)_
徽章我也是考虑到绘画版权的所以经常在更换图标，Dropbox 存着所有已用过图标的 PS 源文件，不过是没放出来。（要不自己画？
论坛的话...难不成还得自己...
如果你们觉得这个小圈子还有点聊的话那我就去建群了，个人比较喜欢 Telegram 离不开 sticker 了

PS:我看了看词典，还是改用徽章这个词吧..勋章，感觉也没做出什么成就来

投个票吧：
赞成建 favicon repo 用 😄
赞用 Telegram 然后聊天讨论新图标用 🎉
赞成论坛或 Gitter 用 ❤️
